### ISSUE TITLE
Create Login text box for username and password

### ISSUE THREAD

**Issue by ndohertyjr** [cshangout/CS-Hangout-Website#15]
As a user, I would need to log into the site by providing a username and password.  The password should not be visible when I am typing and should accept a max of 24 characters.

Acceptance Criteria:
* Create a User Credentials Login Component
* Component should contain an input field for username
* Component should contain an input field for password
* Username field should require email
* Username field should be no longer than 40 characters
* Password component should be no longer than 24 characters and a minimum of 8 characters
* Component should be added to the Login Landing Page Component

**Comment by EidanGar** [comment]
Hello @ndohertyjr ! I read your readme, is this for SNHU students only?

**Comment by ndohertyjr** [comment]
Hey @EidanGar this is a project for members of the SNHU student discord.  We don't necessarily restrict membership of the discord but it's generally SNHU students, alumni, and prospective students.  If you are interested in working on the project I'm not opposed but you'd have to join the discord because that's how we'll be doing sessions to talking about refinement and code questions.

Here's an inv link that is good for a week: https://discord.gg/tDQckZJt

**Comment by EidanGar** [comment]
Hi @ndohertyjr , I appreciate the opportunity to work on this issue. However, since it is intended for students to practice then I don't want to take away from their learning experience. If there is material available on a higher level, I would be interested in potentially joining the discord to discuss and participate. Thank you for considering me.
